services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-data:/etc/resty-auto-ssl
    network_mode: host
    environment:
      ALLOWED_DOMAINS: "nikpetrich.com" # The domain of your server
      SITES: "dice.nikpetrich.com=http://localhost:1111;inventory.nikpetrich.com=http://localhost:1112;" # The subdomains and their corresponding ports

volumes:
  ssl-data:
